[package]
name = "rhymomatic"
version = "0.1.0"
authors = ["Caleb Hattingh <caleb.hattingh@gmail.com>"]
edition = "2018"

[dependencies]
paw = "1.0.0"
structopt = { version = "0.3.21", features = [ "paw" ] }
regex = "1.5.3"
anyhow = "1.0.40"
